### PR TITLE
allow opal 0.8

### PR DESCRIPTION
**Pull request by catmando**
tests pass just fine

### CODE REVIEW

**Comment by elia** [comment]
👍🏼 thanks

**Comment by zetachang** [comment]
Does `opal-rails` actually support opal 0.8,?  Got error below while running test

```
undefined method `load_asset' for Opal::Sprockets:Module
```

Seems like it's invoking a new method introduced in 0.9 at line https://github.com/opal/opal-rails/blob/ddc65773ea166339a0da43684f26df713ef99a31/app/helpers/opal_helper.rb#L19

**Comment by elia** [comment]
@zetachang I think you're right, https://github.com/opal/opal-rails/blob/v0.9.0/app/helpers/opal_helper.rb#L19 need to fix and re-release… I'd be happy to merge a PR adding a `respond_to?` check :)

**Comment by zetachang** [comment]
@elia , it's so weird that I cannot make the test to use the `OpalHelper#javascript_include_tag` method. Any suggestion on at least making a test case to cover that method?

**Comment by elia** [comment]
@zetachang what did you try so far? Maybe it's a load order issue, or related with rails initializing procedure

**Comment by zetachang** [comment]
Actually I just run the current test suits agains opal 0.8 (using the spec in **integrations** folder), the helper file is _required_ but the helper module is _not included_, (`opal_tag` also cause `undefined method` error).

**Pull request merged**
