### PR TITLE
Lock sprockets-rails due to v3.0.0 nil assets:

### PR DESCRIPTION
**Pull request by ajjahn**
NoMethodError: undefined method `append_path' for nil:NilClass
/home/travis/.rvm/gems/ruby-2.1.5/gems/opal-rails-0.8.0/lib/opal/rails/engine.rb:34:in `block in <class:Engine>'

### CODE REVIEW

**Comment by mibamur** [comment]
it is a bad solution, u know

**Comment by ajjahn** [comment]
@mibamur, this was a patch for a bug that popped up the day sprockets 3 was released. Meaning, the tests suddenly broke even though no code had been changed. At the time this was a perfectly reasonable solution intended to keep this gem working for anyone using using it with sprockets 2.x.x (which was everyone). I believe you can search through the opal gitter history and find a thread between myself and @elia discussing it. 

Of course this wasn't intended to be set in stone forever, and indeed sprockets 3 should be supported.

**Comment by mibamur** [comment]
Thanks for answer.
Now I understand this patch :-)

@ajjahn can you look at this https://github.com/opal/opal-rails/issues/85 and maybe say something

> send me to gitter great idea
PS
thanks to times

**Comment by mibamur** [comment]
https://github.com/opal/opal-rails/issues/82

**Pull request merged**
