### PR TITLE
source maps fix

### PR DESCRIPTION
**Pull request by elia**
related opal PR is opal/opal#722

This should fix most 404 and 500 problems

### CODE REVIEW

**Comment by cantonic** [comment]
Yay, it's working! Thx for all the effort.

There is just one thing: I keep getting `Opal already loaded. Loading twice can cause troubles, please fix your setup.` from `/__OPAL_SOURCE_MAPS__/jquery_ujs.js` in the js console.

**Comment by cantonic** [comment]
and a minor thing i noticed: for testing this I have added a failing line in `app/assets/javascripts/drive/directories.js.rb:5`, but the js console shows kernel.rb as the source file. It is ok, since I can expand the error message and click on `directories.rb`, but I wondered: is it supposed to be like this?

Also I added `puts 'foo'` to `directories.js.rb`, but in the js console `main.rb` is displayed as the source file.

My console output:
screen shot 2015-03-13 at 22 38 46

**Comment by elia** [comment]
@cantonic that's by design, everything is flattened to .rb, this makes it easier to serve stuff from the source maps server. Even if not optimal it makes the system more reliable.

**Comment by cantonic** [comment]
Ah okay, thx for the explanation.

**Pull request merged**
